//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z.Core.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrators
    {
        public int Ad_ID { get; set; }
        public string Ad_AdminAccount { get; set; }
        public string Ad_AdminPassword { get; set; }
        public short Ad_IsDisable { get; set; }
        public short Ad_IsDetele { get; set; }
        public System.DateTime Ad_CreateTime { get; set; }
        public System.DateTime Ad_UpdateTime { get; set; }
    }
}
